### ISSUE TITLE
Als Nutzer möchte ich, dass der window-close-button die gleiche Funktionalität hat wie der Close-Button.

### ISSUE THREAD

**Issue by Langleu** [HPI-SWA-Teaching/SWT16-Project-11#15]

**Comment by pinussilvestrus** [comment]
Ich würde gar keinen Close-Button reinmachen, sondern einfach nur die "closeAction" des ganzen Fensters ansprechen. Dann haben wir nicht zwei Close-Buttons, was eh verhindern würde.

**Comment by pinussilvestrus** [comment]
aimed to solve in #79
