### ISSUE TITLE
Als Nutzer möchte ich, dass alle File- und Directory-Chooser Prozesse plattformunabhängig getestet werden.

### ISSUE THREAD

**Issue by Langleu** [HPI-SWA-Teaching/SWT16-Project-11#46]
Momentan ist es schwierig, die File-Chooser Funktionalität zu testen, weil wir die Fenster-Interaktion nicht testen können. Der Pfad ist außerdem abhängig vom Betriebssystem. Da wir den Dateipfad bei vielen Sachen brauchen, sollten wir das auch ausgiebig testen. Die Frage ist nur wie (1. Die Interaktion im Fenster, 2. plattformunabhängig).

**Comment by pinussilvestrus** [comment]
found this on FileList2ModalDialogTest >> testModalFolderSelector:

window openInWorld: self currentWorld extent: 300@400.
    fileList2 fileListIndex: 1.
    window delete.

**Comment by pinussilvestrus** [comment]
Ergebnis: man kann wohl nur Sachen testen, auf die man zugreifen kann.Die Chooser bedürfen richtige User Interaktion.
