### ISSUE TITLE
Wenn ich mich als Nutzer dazu entschieden habe nicht zu speichern, möchte ich trotzdem noch, dass das Interface benutzbar ist.

### ISSUE THREAD

**Issue by Langleu** [HPI-SWA-Teaching/SWT16-Project-11#52]

**Comment by pinussilvestrus** [comment]
Reproduce: Wenn ein neues Dialogfenster geöffnet wurde (zum Beispiel letzte Loadspec nicht löschbar, Close oder Save-Button-Dialog), verhält sich das Tool merkwürdig. Man kann quasi nichts mehr machen...

**Comment by pinussilvestrus** [comment]
aimed to solve in #79
