### ISSUE TITLE
allready -> already

### ISSUE THREAD

**Issue by cmfcmf** [HPI-SWA-Teaching/SWT16-Project-11#95]
Typo is here: https://github.com/HPI-SWA-Teaching/SWT16-Project-11/blob/dae4dd45f9bc534ba662ac95dd7a59cdff20d590/packages/SWT16-Project11-Core.package/SGILogic.class/instance/saveButtonAction.st#L7

Nice presentation so far :100: :smile:

**Comment by pinussilvestrus** [comment]
👍  👍
